include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
analyzer:
  errors: 
    one_member_abstracts: ignore
    public_member_api_docs: ignore
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart]