name: flutter_resume_builder_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  dartz:  ^0.10.1 
  device_preview: ^1.1.0
  dio: ^5.4.2+1
  easy_localization: ^3.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  pdf: ^3.10.8

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/images/png/
    - assets/images/png/navbar/
    - assets/images/png/resume/
    - assets/images/svg/
    - assets/lang/
    - assets/lotties/
