name: fixresume
description: "FixResume is a Flutter application that helps you create a
  professional resume in minutes. It is a cross-platform application that is
  available on Android, iOS, and *Web. It is built using Flutter and Supabase. "

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.1
  cropperx: ^1.1.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  device_preview: ^1.1.0
  dio: ^5.4.2+1
  easy_localization: ^3.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  injectable: ^2.4.2
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  printing: ^5.12.0
  purchases_flutter: ^6.30.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.0
  signin_with_linkedin: ^1.0.1
  supabase_flutter: ^2.5.3
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/images/app/
    - assets/images/png/
    - assets/images/png/navbar/
    - assets/images/png/resume/
    - assets/images/svg/
    - assets/lang/
    - assets/lotties/
    - assets/files/html/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app/app-icon-500.png"
